# Generated by Django 3.0.5 on 2020-04-23 08:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(choices=[('SSEA', 'SSEA'), ('programmers', 'programmers')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('problem_content', models.TextField()),
                ('coding_content', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
